server:
  port: ${db_user_port}
#jdbc:postgresql://localhost:5432/SocialMediaDB
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_postgre_user_url}
    username: ${db_postgre_username}
    password: ${db_postgre_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  feign:
    auth: http://localhost:8090/api/v1/auth
    post: http://localhost:8092/api/v1/post