server:
  port: 8092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service
  data:
    mongodb:
      host: localhost
      port: 28000
      username: "Java4Admin"
      password: "123456789"
      database: postDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
myapplication:
  feign:
    auth: http://localhost:8090/api/v1/auth
    user: http://localhost:8091/api/v1/user
    elastic: http://localhost:8099/api/v1/elastic

jwt:
  secretKey: "java4123"
  issuer: "mustafa"
  audience: "bilgeadam"
rabbitmq:
  queueRegister: register-queue
  exchange-user: user-exchange
  bindingKeyUpdate: update-key
  queueUpdate: update-queue


