server:
  port: 8091

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 28000
      username: "Java4Admin"
      password: "123456789"
      database: java4UserDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
myapplication:
  feign:
    auth: http://localhost:8090/api/v1/auth
    post: http://localhost:8092/api/v1/post
    elastic: http://localhost:8099/api/v1/elastic


